# Generated by Django 3.0.8 on 2021-02-27 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fac', '0002_facturadet_facturaenc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facturaenc',
            old_name='Cliente',
            new_name='cliente',
        ),
    ]
