# Generated by Django 3.0.8 on 2021-02-28 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fac', '0003_auto_20210226_2329'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facturadet',
            options={'permissions': [('sup_caja_facturadet', 'Permisos de Supervisor de Caja Detalle')], 'verbose_name': 'Detalle Factura', 'verbose_name_plural': 'Detalles de Facturas'},
        ),
        migrations.AlterModelOptions(
            name='facturaenc',
            options={'permissions': [('sup_caja_facturaenc', 'Permisos de Supervisor de Caja Encabezado')], 'verbose_name': 'Encabezado Factura', 'verbose_name_plural': 'Encabezado de Facturas'},
        ),
    ]
